name: FastAPI CI/CD
on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: "3.7"

      # Install Python Virtual Environment
      - name: Install virtualenv
        run: pip3 install virtualenv

      # Setup Virtual Environment
      - name: Cache Virtual Environment
        uses: actions/cache@v4  # Updated to v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Build Virtual Environment (only if it does not already exist)
      - name: Activate Virtual ENV
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      # Run Tests
      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest

      # Create archive of dependency files
      - name: Archive dependencies
        run: |
          cd .venv/lib/python3.7/site-packages
          zip -r9 ${GITHUB_WORKSPACE}/dependencies.zip .

      # Add API files to Zip
      - name: Add API files to Zip
        run: |
          cd ${GITHUB_WORKSPACE}
          zip -r9 dependencies.zip .
          mv dependencies.zip ${GITHUB_WORKSPACE}/dependencies.zip

      # Upload the zip file as an artifact
      - name: Upload dependencies.zip
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: dependencies
          path: ${GITHUB_WORKSPACE}/dependencies.zip
