name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      # Cache Virtual Environment
      - name: Cache Virtual Environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Create and Activate Virtual Environment (if needed)
      - name: Setup Virtual Environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # Run Tests
      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest

      # Create archive of dependency files (Best Practices)
      - name: Archive dependencies
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/artifacts
          cd .venv/lib/python3.10/site-packages
          zip -r ${GITHUB_WORKSPACE}/artifacts/dependencies.zip .

      # Add API files to Zip
      - name: Add API files to Zip
        run: |
          cd ${GITHUB_WORKSPACE}
          zip -r artifacts/dependencies.zip .

      # Upload the zip file as an artifact
      - name: Upload dependencies.zip
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: ${GITHUB_WORKSPACE}/artifacts/dependencies.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      # Install AWS CLI
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Download dependencies.zip artifact
      - name: Download dependencies.zip
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: artifacts  # Ensuring correct path

      # Upload to AWS S3
      - name: Upload to S3
        run: |
          aws s3 cp artifacts/dependencies.zip s3://fastapiride/dependencies.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Deploy to AWS Lambda (Ensure this step is properly configured)
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name fastapi --s3-bucket fastapiride --s3-key dependencies.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
