name: FastAPI CI/CD
on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      # Cache Virtual Environment
      - name: Cache Virtual Environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Create and Activate Virtual Environment (if needed)
      - name: Setup Virtual Environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # Run Tests
      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest

      # Create archive of dependency files
      - name: Archive dependencies
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/artifacts
          cd .venv/lib/python3.10/site-packages
          zip -r ${GITHUB_WORKSPACE}/artifacts/dependencies.zip .

      # Add API files to Zip
      - name: Add API files to Zip
        run: |
          cd ${GITHUB_WORKSPACE}
          zip -r artifacts/dependencies.zip .

      # Upload the zip file as an artifact
      - name: Upload dependencies.zip
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: ${GITHUB_WORKSPACE}/artifacts/dependencies.zip
