name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv

      # Cache Virtual Environment
      - name: Cache Virtual Environment
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      # Create and Activate Virtual Environment (if needed)
      - name: Setup Virtual Environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      
      - name: Clean up pyc files
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} +

      # Run Tests (specify test directory to avoid 0 tests collected)
      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest ./test

      # Create archive of dependency files (Fixed paths)
      - name: Archive dependencies
        run: |
          mkdir -p artifacts
          cd .venv/lib/python3.9/site-packages
          ls -lah  
          if [ "$(ls -A .)" ]; then
            zip -r artifacts/api.zip ./*
            echo "Artifact api.zip successfully created!"
          else
            echo "No files found, skipping zip creation."
          fi

      # Add API files to Zip
      - name: Add API files to Zip
        run: |
          cd ${GITHUB_WORKSPACE}/api
          zip -r ../artifacts/api.zip .

      # Upload the zip file as an artifact
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts/api.zip
          retention-days: 5

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      # Install AWS CLI (Official Method)
      - name: Install or Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      # Configure AWS credentials
      - name: Set up AWS credentials
        run: |
          echo "Configuring AWS credentials..."
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Download zip file artifact
      - name: Download Lambda api.zip
        uses: actions/download-artifact@v4
        with:
          name: api
          path: artifacts

      # Upload to AWS S3
      - name: Upload to S3
        run: |
          aws s3 cp artifacts/api.zip s3://fastapiride/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      # Deploy to AWS Lambda
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name fastapi --s3-bucket fastapiride --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}